language: c
script: make
compiler: gcc
after_success:
- openssl aes-256-cbc -K $encrypted_329f82cf70e1_key -iv $encrypted_329f82cf70e1_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
sudo: required
services:
- docker
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
